// Regenerates docs/guides/use-cases.mdx from USE_CASES in src/usecases.ts (the single source).
// Run after editing use cases: node scripts/gen-use-cases.ts
import { writeFileSync } from "node:fs";
import { GUARDRAIL, USE_CASES, type UseCase } from "../src/usecases.ts";

const LABEL: Record<string, string> = { postcard_4x6: "Postcard 4×6", postcard_6x9: "Postcard 6×9", postcard_6x11: "Postcard 6×11", letter: "Letter", letter_certified: "Certified letter", letter_certified_rr: "Certified letter + return receipt" };
const section = (u: UseCase) => `## ${u.title}\n\n${u.why}\n\n\`\`\`text\n${u.prompt}\n\`\`\`\n\n*${LABEL[u.product]}*${u.note ? `. ${u.note}` : ""}\n`;

const mdx = `---
title: "Use cases"
description: "What people send with Sendpaper, with prompts you can paste into your agent."
---

{/* Generated by scripts/gen-use-cases.ts from src/usecases.ts. Edit there, then rerun. */}

Letters that need proof, and cards that deserve paper. Each prompt works as-is in Codex, Muse or Claude once Sendpaper is connected.

# When you need proof it arrived

Certified Mail with tracking and proof of delivery. Write it with your agent, or upload a PDF.

<Note>${GUARDRAIL}</Note>

${USE_CASES.filter((u) => u.group === "proof").map(section).join("\n")}
# Personal mail

${USE_CASES.filter((u) => u.group === "personal").map(section).join("\n")}`;

writeFileSync(new URL("../docs/guides/use-cases.mdx", import.meta.url), mdx);
console.log(`wrote docs/guides/use-cases.mdx (${USE_CASES.length} use cases)`);
